apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: messaging
type: Opaque
stringData:
  host: "amqp://guest:guest@rabbitmq.messaging.svc.cluster.local:5672/"
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: rabbitmq-trigger-auth
  namespace: messaging
spec:
  secretTargetRef:
    - parameter: host
      name: rabbitmq-secret
      key: host
