apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-consumer-scaler
  namespace: messaging
spec:
  scaleTargetRef:
    name: rabbitmq-consumer
  minReplicaCount: 1
  maxReplicaCount: 10
  pollingInterval: 30
  cooldownPeriod: 60
  triggers:
    - type: rabbitmq
      metadata:
        protocol: "amqp"
        queueName: "task-queue"
        mode: "QueueLength"
        value: "5"
        vhostName: "/"
      authenticationRef:
        name: rabbitmq-trigger-auth
